"use client";

import React from "react";
import { Check, X, ShieldAlert, Sparkles } from "lucide-react";

export default function ComparisonTable() {
  const comparisons = [
    {
      feature: "Evaluation Modality",
      traditional: "Text resumes and keyword checkers",
      zai: "Simultaneous video, speech prosody, and semantic context",
      supported: true
    },
    {
      feature: "Behavioral Analytics",
      traditional: "Self-reported questionnaires",
      zai: "Continuous stress tracking, speech hesitancy, micro-saccades",
      supported: true
    },
    {
      feature: "Identity Verification",
      traditional: "One-off email/SMS checking",
      zai: "Live passport validation and video oximetry liveness detection",
      supported: true
    },
    {
      feature: "Stress Adaptation",
      traditional: "Static assessments / generic quizzes",
      zai: "Adapts to stress thresholds during architectural deep-dives",
      supported: true
    },
    {
      feature: "Dossier Latency",
      traditional: "Manual review takes days / weeks",
      zai: "Autogenerated structured dossier within 40ms of call exit",
      supported: true
    },
    {
      feature: "Resume Gameability",
      traditional: "Highly vulnerable to ChatGPT keyword stuffing",
      zai: "Un-gameable live biological and logical response tracking",
      supported: false // Zai handles gameability, traditional is vulnerable
    }
  ];

  return (
    <section id="comparison" className="py-20 border-t border-white/5 bg-[#070707] relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white">
            How Zai Redefines Evaluation
          </h2>
          <p className="mt-4 text-gray-400 text-sm sm:text-base">
            Why settle for keyword matching? Compare the depth of Zai's biometric insights against traditional applicant screening methods.
          </p>
        </div>

        {/* Table Layout */}
        <div className="max-w-4xl mx-auto overflow-hidden rounded-2xl border border-white/5 glass-card">
          <div className="grid grid-cols-1 md:grid-cols-12 border-b border-white/5 bg-white/[0.01]">
            <div className="md:col-span-4 p-4 text-left text-xs font-bold font-mono uppercase tracking-wider text-gray-500">
              Evaluation Vectors
            </div>
            <div className="md:col-span-4 p-4 text-left text-xs font-bold font-mono uppercase tracking-wider text-gray-500">
              Traditional Screening
            </div>
            <div className="md:col-span-4 p-4 text-left text-xs font-bold font-mono uppercase tracking-wider text-accent-blue bg-accent-blue/5 border-l border-white/5 flex items-center gap-1.5">
              <Sparkles size={12} className="text-accent-blue" />
              <span>Zai AI Engine</span>
            </div>
          </div>

          <div className="divide-y divide-white/5">
            {comparisons.map((item, idx) => (
              <div key={idx} className="grid grid-cols-1 md:grid-cols-12 items-center hover:bg-white/[0.01] transition-colors">
                {/* Feature Vector label */}
                <div className="md:col-span-4 p-4 font-semibold text-xs text-white text-left font-mono">
                  {item.feature}
                </div>
                
                {/* Traditional text */}
                <div className="md:col-span-4 p-4 text-xs text-gray-400 text-left flex items-start gap-2">
                  <X size={14} className="text-rose-500 shrink-0 mt-0.5" />
                  <span>{item.traditional}</span>
                </div>
                
                {/* Zai text */}
                <div className="md:col-span-4 p-4 text-xs text-white text-left flex items-start gap-2 bg-accent-blue/[0.02] border-l border-white/5">
                  <Check size={14} className="text-accent-emerald shrink-0 mt-0.5" />
                  <span className="font-medium">{item.zai}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  );
}
